brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

autoCreateTopicEnable = true
autoCreateSubscriptionGroup = true

listenPort = 10911
brokerIP1=0.0.0.0
namesrvAddr = rocketmq-namesrv:9876

# 存储路径配置，解决定时任务空指针重启
storePathRootDir=E:/rocketmq/store
storePathCommitLog=E:/rocketmq/store/commitlog
storePathConsumeQueue=E:/rocketmq/store/consumequeue
storePathScheduleMsg=E:/rocketmq/store/schedule
storePathIndex=E:/rocketmq/store/index
storePathDeletedFile=E:/rocketmq/store/deleted